alias ls='ls -F'
alias cls='clear'
alias atom='open -a atom'
alias vscode='open -a Visual\ Studio\ Code'
alias grep='grep --color=auto'
alias studio='open -a rstudio'
alias sublime='open -a sublime\ text'
alias cdas='cd ~/studio/academia'
alias cd..='cd ../'
alias pip3='python3 -m pip'
alias matlab='/Applications/MATLAB_R2015b.app/bin/matlab -nodesktop -nodisplay -nosplash -r'
CLICOLOR="xterm-color"
LSCOLORS="gxfxcxdxcxegedabagacad"
export CLICOLOR='true'
export CLICOLOR LSCOLORS
#export PS1="\[\e[0;31m\]\u@\[\e[m\e[0;34m\]\h\[\e[m \e[0;32m\]\W \$\[\e[m\]"
alias jupyter='/Library/Frameworks/Python.framework/Versions/3.6/bin/jupyter'
alias siete='source activate siete'
# added by Miniconda3 installer
export PATH="/Users/jemmy/miniconda3/bin:$PATH"
#export PATH="/usr/local/bin:$PATH"
eval $(thefuck --alias)
