set encoding=utf-8
set nu
set ai
set cursorline
set tabstop=4
set shiftwidth=4
set t_Co=256
set bg=dark
syntax enable
set ruler
colorscheme gruvbox
execute pathogen#infect()
set splitright

" Enable folding
set foldmethod=indent
set foldlevel=99

nnoremap <silent> <F5> :NERDTree<R>
filetype plugin indent on
syntax on
set backspace=indent,eol,start
let g:airline#extensions#tabline#enabled=1
let g:airline_theme='term'
